name: open-api
services:
  mysql:
    image: 'mysql:8.4.7'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"