name: open-api-ci-cd
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-api-jar
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: open-api-jar
          path: artifact

      - name: Copy jar to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          proxy_host: ${{ secrets.HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.SSH_KEY }}
          source: "artifact/*.jar"
          target: "~/open-api"

      - name: Restart app on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          proxy_host: ${{ secrets.HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/open-api
            sudo -S fuser -k -n tcp 8080||true
            export OPEN_API_KEY="${{ secrets.OPEN_API_KEY }}"
            export AI_API_KEY="${{ secrets.AI_API_KEY }}"
            export MYSQL_HOST="${{ secrets.MYSQL_HOST }}"
            export MYSQL_DATABASE="${{ secrets.MYSQL_DATABASE }}"
            export MYSQL_USERNAME="${{ secrets.MYSQL_USERNAME }}"
            export MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}"
            export REDIS_HOST="${{ secrets.REDIS_HOST }}"
            export REDIS_PORT="${{ secrets.REDIS_PORT }}"
            nohup java -Duser.timezone=Asia/Seoul -jar -Dspring.profiles.active=prod ~/open-api/artifact/open-api-v1.jar > ~/open-api/open-api.log 2>&1 &